### ISSUE TITLE
Feature: Frontend for the backend `scraper.py`

### ISSUE THREAD

**Issue by abhirajadhikary06** [pythonprogramming-development/Web-Scraping-with-Selenium-and-Python#17]
@sunny7899 Your project is awesome and helpful.
If there would be a frontend built on Flask and styling and all could de done in HTML,CSS,Js then would give users a better access and usability.
**If you would assign me the I could built the complete frontend for you and connect it to backend.** 
I would also like to bring to your notice that from then onwards the `scraper.py` file will be not under use a new `App.py` handling the Flask framework will be in use.

Next you could host it using PythonAnywhere

**Comment by sunny7899** [comment]
@abhirajadhikary06 can you review your code changes its showing 4000+ files change whats that please fix it ASAP

**Comment by abhirajadhikary06** [comment]
Okay so don't merge it for now. Let me review those files. **Actually all the files are the dependencies of react-radiax-ui**

**Comment by sunny7899** [comment]
@abhirajadhikary06 add it in gitignore or update the solution its not correct
